name: CI

on: [pull_request, push]

jobs: 
    build-test:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            - name: Using Node.js
              uses: actions/setup-node@v2
              with: 
                node-version: 22.
            - name: Cypress Tests 
              run: |
                npm run build
                npm run dev

              
           